### ISSUE TITLE
Add custom control feature "aspectRatio" and "scaleFromCenter"

### ISSUE THREAD

**Issue by brutalsignature** [skmail/vue-free-transform#2]
Hello! Thank you for your plugin! Could you add custom control feature "aspectRatio" and "scaleFromCenter", so that i can manage it in props, like that:
<FreeTransform :aspect-ratio="aspectRatio" :scale-from-center=" scaleFromCenter "/>
or something similar...

Thank you!)

**Comment by skmail** [comment]
:aspect-ratio="false" and :scale-from-center="false" has been added
