### ISSUE TITLE
Request: Use with jQuery or a version in plain JS would be awesome !

### ISSUE THREAD

**Issue by Smashr** [skmail/vue-free-transform#9]
Hey,

The component looks awesome !

It would be great if there were a version to use with jQuery or in plain js, that provides the same functionality but without vue or react. Any plans ?

Thanks.
Norman.

**Comment by Smashr** [comment]
Sorry, had to post this as an issue just so I could get in touch .., although its only a request. :)

**Comment by skmail** [comment]
Hey, glade to hear you liked it.

This is just a wrapper, You can build your own implementation using the underlying library:

https://github.com/skmail/free-transform

**Comment by Smashr** [comment]
Thank you for the link.

I really need this to work with jQuery ... any pointers on how to go about building my own implementation would be awesome. I'll try and figure out, but I may end up spending a lot less time if there is some direction before I start. 

I still consider my expertise with js average, so any help or direction coming from you would be highly welcome.

I have been looking at the library before, but it didn't seem very straightforward to implement in jQuery.

Thank you in advance ! :)

**Comment by skmail** [comment]
There you go, I've implemented the top-left and top-right corners scaling, other corners, dragging and rotation is same concept.
https://codesandbox.io/s/4wyk22mvn4

you can checkout the library to copy-paste the dragging and rotation code
https://github.com/skmail/free-transform

**Comment by Smashr** [comment]
Thank you so much for the head start, you're awesome !

It looks great, I will be able to get this implemented from here IA. :)

Thank you once again ! :)
